version: '3'
services:
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
  build:       
      context: https://github.com/aschiffler/ml5nodered.git
      dockerfile: Dockerfile